name: frontend
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  paper_elements: '>=0.4.0 <0.5.0'
  polymer: '>=0.15.0 <0.16.0'
  rate_limit: any
transformers:
- polymer:
    entry_points: web/index.html
