name: knihovna_frontend
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  core_elements: "<=0.4.0+5"
  paper_elements: any
  polymer: "<=0.15.1+4"
  rate_limit: any
  route: any
  simple_preprocessor: any
transformers:
- simple_preprocessor
- polymer:
    entry_points: web/index.html
