application: tisic-knih
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static_admin/
  static_dir: static_admin

- url: /admin/.*
  login: admin
  script: admin.application

- url: /autocomplete/.*
  script: main.application

- url: /query/.*
  script: main.application

- url: /
  static_files: static/index.html
  upload: static

- url: /
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

builtins:
- deferred: on