name: knihovna_frontend
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.12.0 <0.13.0'
transformers:
- polymer:
    entry_points: web/knihovna_frontend.html
