name: knihovna_frontend
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: any
  rate_limit: any
transformers:
- polymer:
    entry_points: web/knihovna_frontend.html
